### PR TITLE
Upgrade to mesos 1.2.0 and marathon 1.4.1

### PR DESCRIPTION
**Pull request by brunomacf**
THIS IS NOT FULLY WORKING YET. I can deploys the “sava” blueprint, i can see it registering in marathon, but it seems that vamp (or someone else) is registering a wrong ip address to the deployed service (it’s registering the docker container id instead of any valid ip) leading to haproxy reload error through confd and not showing metrics in deployments ui console. Other things to note are (probably each one deserves it own particular issue here in github):

1) Since supervisor is in charge to start all the process in quick-start container and there are no priorities provided, then sometimes VGA starts before Vamp, leading to "zk: node does not exist" error because required keys does not exists yet in zookeeper (that are created by vamp). When i start Vamp by hand before VGA i no longer see that error message.

2) Often Vamp is trying to create the same workflow multiple times like the logs indicate:

```
21:21:11.124 | INFO  | i.v.l.a.ArtifactInitializationActor      | er/vamp/artifact-initialization-actor-20 | Creating artifact: breeds/health
21:21:11.262 | INFO  | i.v.l.a.ArtifactInitializationActor      | er/vamp/artifact-initialization-actor-20 | Creating artifact: breeds/allocation
21:21:11.263 | INFO  | i.v.l.a.ArtifactInitializationActor      | er/vamp/artifact-initialization-actor-20 | Creating artifact: breeds/metrics
21:21:11.264 | INFO  | i.v.l.a.ArtifactInitializationActor      | er/vamp/artifact-initialization-actor-20 | Creating artifact: workflows/health
21:21:11.265 | INFO  | i.v.l.a.ArtifactInitializationActor      | er/vamp/artifact-initialization-actor-20 | Creating artifact: breeds/kibana
21:21:11.288 | INFO  | i.v.l.a.ArtifactInitializationActor      | er/vamp/artifact-initialization-actor-20 | Creating artifact: workflows/allocation
21:21:11.295 | INFO  | i.v.l.a.ArtifactInitializationActor      | er/vamp/artifact-initialization-actor-20 | Creating artifact: workflows/kibana
21:21:11.304 | INFO  | i.v.l.a.ArtifactInitializationActor      | er/vamp/artifact-initialization-actor-20 | Creating artifact: workflows/metrics
21:21:13.380 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'health'.
21:21:13.384 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'allocation'.
21:21:13.397 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'metrics'.
21:21:13.943 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: allocation
21:21:14.033 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: health
21:21:14.063 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: metrics
21:21:16.142 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'health'.
21:21:16.143 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'allocation'.
21:21:16.146 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'metrics'.
21:21:16.423 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: allocation
21:21:16.493 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: health
21:21:16.587 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: metrics
21:21:19.134 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'health'.
21:21:19.146 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'allocation'.
21:21:19.147 | INFO  | io.vamp.operation.workflow.WorkflowActor | akka://vamp/user/vamp/workflow-actor-15  | Triggering workflow: 'metrics'.
21:21:19.411 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: metrics
21:21:19.453 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: allocation
21:21:19.517 | INFO  | i.v.c.marathon.MarathonDriverActor       | /vamp/user/vamp/marathon-driver-actor-22 | marathon create workflow: health
```

This is causing the following type of erros in marathon:

```
[2017-04-11 21:21:16,775] ERROR Exception while processing request (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$b12a9fae:qtp265330243-35)
mesosphere.marathon.ConflictingChangeException: An app with id [/vamp/workflow-health] already exists.
    at mesosphere.marathon.api.v2.AppsResource$$anonfun$create$1$$anonfun$apply$3$$anonfun$mesosphere$marathon$api$v2$AppsResource$$nestedInanonfun$$nestedInanonfun$$createOrThrow$1$1.apply(AppsResource.scala:87)
    at mesosphere.marathon.api.v2.AppsResource$$anonfun$create$1$$anonfun$apply$3$$anonfun$mesosphere$marathon$api$v2$AppsResource$$nestedInanonfun$$nestedInanonfun$$createOrThrow$1$1.apply(AppsResource.scala:87)
    at scala.Option.map(Option.scala:146)
    at mesosphere.marathon.api.v2.AppsResource$$anonfun$create$1$$anonfun$apply$3.mesosphere$marathon$api$v2$AppsResource$$nestedInanonfun$$nestedInanonfun$$createOrThrow$1(AppsResource.scala:87)
    at mesosphere.marathon.api.v2.AppsResource$$anonfun$create$1$$anonfun$apply$3$$anonfun$3.apply(AppsResource.scala:90)
    at mesosphere.marathon.api.v2.AppsResource$$anonfun$create$1$$anonfun$apply$3$$anonfun$3.apply(AppsResource.scala:90)
    at mesosphere.marathon.state.RootGroup.updateApp(RootGroup.scala:250)
    at mesosphere.marathon.core.group.impl.GroupManagerDelegate$$anonfun$updateApp$1.apply(GroupManagerDelegate.scala:78)
    at mesosphere.marathon.core.group.impl.GroupManagerDelegate$$anonfun$updateApp$1.apply(GroupManagerDelegate.scala:78)
    at mesosphere.marathon.core.group.impl.GroupManagerActor$$anonfun$mesosphere$marathon$core$group$impl$GroupManagerActor$$getUpgrade$1$$anonfun$3.apply(GroupManagerActor.scala:146)
    at mesosphere.marathon.core.group.impl.GroupManagerActor$$anonfun$mesosphere$marathon$core$group$impl$GroupManagerActor$$getUpgrade$1$$anonfun$3.apply(GroupManagerActor.scala:145)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### CODE REVIEW

**Comment by olafmol** [comment]
@brunomacf regarding 2: is there a specific event that you can see before this "re-init/retriggering" action?

**Comment by dragoslav** [comment]
As long `2)` is recoverable it is fine. Vamp tries to start workflow as long the workflow is not started yet - we can tweak configuration parameters to avoid (as many of these) errors, or add additional checks in Marathon driver implementation.

**Comment by brunomacf** [comment]
@olafmol and @dragoslav indeed `2` is totally fine... it just tries to create 3 times and then stops.

**Comment by brunomacf** [comment]
One additional consideration: As you can see, i had to modify run.sh to prevent mounting docker binary inside container in quick-start... it's seems that macOS has some permission issues to so. What i did instead was to install docker inside the container and let it use the mounted docker.sock to communicate with host docker. Maybe we should do this in all other clique-* containers.

**Comment by olafmol** [comment]
@brunomacf is this merge-able, or does something needs to be fixed to make it work?

**Comment by brunomacf** [comment]
@olafmol I'm still tracking down the issue with haproxy to make this work. Sorry about this delay, but it's more difficult than i thought.

**Comment by ItsMeijers** [comment]
Closing this PR due to no further developments and upgrading the versions in the meanwhile.

**Pull request closed without merging**
